package routers

import (
	"eme/controllers"
	"eme/pkg/config"

	// docs is generated by Swag CLI, you have to import it.
	_ "eme/docs"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// InitRouter 初始化路由
func InitRouter() *gin.Engine {
	if config.RunMode != "dev" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(gin.LoggerWithWriter(gin.DefaultWriter))
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	apiv1 := r.Group("/v1")
	{
		apiv1.GET("/users", controllers.UserGet)
		apiv1.POST("/users", controllers.UserAdd)

		apiv1.GET("/role", controllers.RoleGet)
		apiv1.GET("/role/:id", controllers.RoleGetByID)
		apiv1.POST("/role", controllers.RoleAdd)
		apiv1.PUT("/role", controllers.RoleUpdate)
		apiv1.DELETE("/role/:id", controllers.RoleDel)
	}
	return r
}
